Better debugging for niv-update

diff --git a/.github/workflows/niv-update.yml b/.github/workflows/niv-update.yml
--- a/.github/workflows/niv-update.yml
+++ b/.github/workflows/niv-update.yml
@@ -28,28 +28,32 @@ jobs:
             git reset --hard origin/master
             niv update $source
             if test -n "$(git status)"; then
-              git config --local user.email 'info@eigenvalue.net'
-              git config --local user.name 'Peter Kolloch, Bot'
-              n=0
-              until [ $n -ge 5 ]
-              do
-                git commit -m 'niv update ${{matrix.source}}' -a
-                ./run_tests.sh || {
-                  echo "Tests failed. Skip updating $source."
-                  break
-                }
-                git push && break
-                n=$[$n+1]
-                sleep 1
-                # Another try
-                git fetch
-                git reset --hard origin/master
-                niv update ${{matrix.source}}
-              done
-              if [ $n -ge 5 ]; then
-                echo "gave up after 5 tries"
-                exit 1
-              fi
+              (
+                set -x
+                git --no-pager diff HEAD
+                git config --local user.email 'info@eigenvalue.net'
+                git config --local user.name 'Peter Kolloch, Bot'
+                n=0
+                until [ $n -ge 5 ]
+                do
+                  git commit -m 'niv update ${{matrix.source}}' -a
+                  ./run_tests.sh || {
+                    echo "Tests failed. Skip updating $source."
+                    break
+                  }
+                  git push && break
+                  n=$[$n+1]
+                  sleep 1
+                  # Another try
+                  git fetch
+                  git reset --hard origin/master
+                  niv update ${{matrix.source}}
+                done
+                if [ $n -ge 5 ]; then
+                  echo "gave up after 5 tries"
+                  exit 1
+                fi
+              )
             else
               echo "no change for $source"
             fi
